// Question Types
// 1. MCQs | Multiple Choice | single

const QuizData = {
  topic: '四柱推命',
  level: '初級〜上級',
  questions: [
    {
      question: '子と支合になる地支は何ですか？',
      choices: ['卯', '午', '丑', '未'],
      type: 'MCQs',
      correctAnswer: '丑',
    },
    {
      question: '丑と支合になる地支は何ですか？',
      choices: ['未', '子', '戌', '巳'],
      type: 'MCQs',
      correctAnswer: '子',
    },
    {
      question: '寅と支合になる地支は何ですか？',
      choices: ['亥', '申', '戌', '辰'],
      type: 'MCQs',
      correctAnswer: '亥',
    },
    {
      question: '卯と支合になる地支は何ですか？',
      choices: ['戌', '丑', '酉', '子'],
      type: 'MCQs',
      correctAnswer: '戌',
    },
    {
      question: '辰と支合になる地支は何ですか？',
      choices: ['丑', '未', '酉', '戌'],
      type: 'MCQs',
      correctAnswer: '酉',
    },
    {
      question: '巳と支合になる地支は何ですか？',
      choices: ['未', '辰', '亥', '申'],
      type: 'MCQs',
      correctAnswer: '申',
    },
    {
      question: '午と支合になる地支は何ですか？',
      choices: ['巳', '未', '子', '亥'],
      type: 'MCQs',
      correctAnswer: '未',
    },
    {
      question: '未と支合になる地支は何ですか？',
      choices: ['申', '寅', '丑', '午'],
      type: 'MCQs',
      correctAnswer: '午',
    },
    {
      question: '申と支合になる地支は何ですか？',
      choices: ['寅', '巳', '未', '亥'],
      type: 'MCQs',
      correctAnswer: '巳',
    },
    {
      question: '酉と支合になる地支は何ですか？',
      choices: ['辰', '戌', '亥', '卯'],
      type: 'MCQs',
      correctAnswer: '辰',
    },
    {
      question: '戌と支合になる地支は何ですか？',
      choices: ['辰', '申', '卯', '午'],
      type: 'MCQs',
      correctAnswer: '卯',
    },
    {
      question: '亥と支合になる地支は何ですか？',
      choices: ['寅', '未', '巳', '辰'],
      type: 'MCQs',
      correctAnswer: '寅',
    },
    {
      question: '子と冲になる地支は何ですか？',
      choices: ['卯', '丑', '酉', '午'],
      type: 'MCQs',
      correctAnswer: '午',
    },
    {
      question: '丑と冲になる地支は何ですか？',
      choices: ['子', '未', '戌', '辰'],
      type: 'MCQs',
      correctAnswer: '未',
    },
    {
      question: '辰と冲になる地支は何ですか？',
      choices: ['酉', '未', '丑', '戌'],
      type: 'MCQs',
      correctAnswer: '戌',
    },
    {
      question: '寅と冲になる地支は何ですか？',
      choices: ['巳', '亥', '申', '酉'],
      type: 'MCQs',
      correctAnswer: '申',
    },
    {
      question: '亥と冲になる地支は何ですか？',
      choices: ['午', '辰', '巳', '申'],
      type: 'MCQs',
      correctAnswer: '巳',
    },
    {
      question: '卯と冲になる地支は何ですか？',
      choices: ['酉', '戌', '申', '午'],
      type: 'MCQs',
      correctAnswer: '酉',
    },
    {
      question: '亥と冲になる地支は何ですか？',
      choices: ['寅', '申', '巳', '辰'],
      type: 'MCQs',
      correctAnswer: '巳',
    },
    {
      question: '甲と干合になる天干は何ですか？',
      choices: ['癸', '丁', '辛', '己'],
      type: 'MCQs',
      correctAnswer: '己',
    },
    {
      question: '乙と干合になる天干は何ですか？',
      choices: ['庚', '戊', '丙', '壬'],
      type: 'MCQs',
      correctAnswer: '庚',
    },
    {
      question: '丙と干合になる天干は何ですか？',
      choices: ['癸', '辛', '乙', '己'],
      type: 'MCQs',
      correctAnswer: '辛',
    },
    {
      question: '丁と干合になる天干は何ですか？',
      choices: ['甲', '戊', '庚', '壬'],
      type: 'MCQs',
      correctAnswer: '壬',
    },
    {
      question: '戊と干合になる天干は何ですか？',
      choices: ['乙', '丁', '辛', '癸'],
      type: 'MCQs',
      correctAnswer: '癸',
    },
    {
      question: '己と干合になる天干は何ですか？',
      choices: ['壬', '甲', '丙', '庚'],
      type: 'MCQs',
      correctAnswer: '甲',
    },
    {
      question: '庚と干合になる天干は何ですか？',
      choices: ['乙', '癸', '己', '丁'],
      type: 'MCQs',
      correctAnswer: '乙',
    },
    {
      question: '辛と干合になる天干は何ですか？',
      choices: ['丙', '甲', '壬', '戊'],
      type: 'MCQs',
      correctAnswer: '丙',
    },
    {
      question: '壬と干合になる天干は何ですか？',
      choices: ['辛', '乙', '己', '丁'],
      type: 'MCQs',
      correctAnswer: '丁',
    },
    {
      question: '癸と干合になる天干は何ですか？',
      choices: ['丙', '戊', '甲', '庚'],
      type: 'MCQs',
      correctAnswer: '戊',
    },
    {
      question: '三合木局「亥・卯・⚪︎」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['寅', '未', '辰', '戌'],
      type: 'MCQs',
      correctAnswer: '未',
    },
    {
      question: '三合火局「寅・午・⚪︎」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['戌', '未', '辰', '巳'],
      type: 'MCQs',
      correctAnswer: '戌',
    },
    {
      question: '三合金局「⚪︎・酉・丑」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['戌', '申', '丑', '巳'],
      type: 'MCQs',
      correctAnswer: '戌',
    },
    {
      question: '北方合「⚪︎・子・丑」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['酉', '亥', '巳', '申'],
      type: 'MCQs',
      correctAnswer: '亥',
    },
    {
      question: '東方合「寅・卯・⚪︎」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['未', '巳', '戌', '辰'],
      type: 'MCQs',
      correctAnswer: '辰',
    },
    {
      question: '南方合「⚪︎・午・未」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['戌', '辰', '寅', '巳'],
      type: 'MCQs',
      correctAnswer: '巳',
    },
    {
      question: '西方合「申・酉・⚪︎」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['戌', '亥', '丑', '巳'],
      type: 'MCQs',
      correctAnswer: '戌',
    },
    {
      question: '三合金局「⚪︎・酉・丑」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['戌', '申', '丑', '巳'],
      type: 'MCQs',
      correctAnswer: '戌',
    },
    {
      question: '三合水局「⚪︎・子・辰」を構成する地支は何ですか？空欄を埋めてください。',
      choices: ['酉', '亥', '丑', '申'],
      type: 'MCQs',
      correctAnswer: '申',
    },
    {
      question: '甲が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['辰', '丑', '酉', '申'],
      type: 'MCQs',
      correctAnswer: '辰',
    },
    {
      question: '乙が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['丑', '寅', '巳', '戌'],
      type: 'MCQs',
      correctAnswer: '辰',
    },
    {
      question: '丙が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['寅', '辰', '申', '亥'],
      type: 'MCQs',
      correctAnswer: '寅',
    },
    {
      question: '丁が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['子', '巳', '酉', '亥'],
      type: 'MCQs',
      correctAnswer: '巳',
    },
    {
      question: '戊が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['卯', '午', '酉', '子'],
      type: 'MCQs',
      correctAnswer: '午',
    },
    {
      question: '己が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['子', '寅', '酉', '戌'],
      type: 'MCQs',
      correctAnswer: '午',
    },
    {
      question: '庚が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['丑', '寅', '午', '亥'],
      type: 'MCQs',
      correctAnswer: '丑',
    },
    {
      question: '辛が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['子', '辰', '未', '申'],
      type: 'MCQs',
      correctAnswer: '申',
    },
    {
      question: '壬が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['寅', '巳', '戌', '亥'],
      type: 'MCQs',
      correctAnswer: '亥',
    },
    {
      question: '癸が通根する地支を一つ選択してください。候補が複数ある場合は、一番強く通根する地支を選択してください。',
      choices: ['丑', '巳', '未', '戌'],
      type: 'MCQs',
      correctAnswer: '丑',
    },
    {
      question: '日干が乙のとき、壬にあたる通変星は何ですか？',
      choices: ['印綬', '偏印', '食傷', '正財'],
      type: 'MCQs',
      correctAnswer: '傷官',
    },
    {
      question: '日干が丙のとき、癸にあたる通変星は何ですか？',
      choices: ['正官', '偏印', '食傷', '偏官'],
      type: 'MCQs',
      correctAnswer: '正官',
    },
    {
      question: '日干が丁のとき、辛にあたる通変星は何ですか？',
      choices: ['食神', '正財', '偏財', '印綬'],
      type: 'MCQs',
      correctAnswer: '偏財',
    },
    {
      question: '日干が戊のとき、己にあたる通変星は何ですか？',
      choices: ['正財', '比肩', '劫財', '偏財'],
      type: 'MCQs',
      correctAnswer: '劫財',
    },
    {
      question: '日干が己のとき、乙にあたる通変星は何ですか？',
      choices: ['劫財', '偏官', '偏財', '正官'],
      type: 'MCQs',
      correctAnswer: '偏官',
    },
    {
      question: '日干が庚のとき、丙にあたる通変星は何ですか？',
      choices: ['傷官', '印綬', '偏官', '正官'],
      type: 'MCQs',
      correctAnswer: '偏官',
    },
    {
      question: '日干が辛のとき、乙にあたる通変星は何ですか？',
      choices: ['正財', '偏官', '正官', '偏財'],
      type: 'MCQs',
      correctAnswer: '偏財',
    },
    {
      question: '日干が壬のとき、丁にあたる通変星は何ですか？',
      choices: ['偏財', '偏印', '正官', '正財'],
      type: 'MCQs',
      correctAnswer: '正財',
    },
    {
      question: '日干が癸のとき、甲にあたる通変星は何ですか？',
      choices: ['傷官', '印綬', '食傷', '偏印'],
      type: 'MCQs',
      correctAnswer: '傷官',
    },
  ],
}

export default QuizData;